language: cpp

git:
  depth: false

cache:
  directories:
    - $HOME/vcpkg

matrix:
  include:
    - os: linux
      sudo: true
      env:
        - VCPKG_TRIPLET=x64-linux
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8 && $TRAVIS_BUILD_DIR/travis/install_maven.sh && export PATH=$HOME/maven/bin:$PATH"
        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.sh"
        - SYSTEM_TRIPLET=linux
        - PREFERED_ARCHIVE_EXTENSION=tar.gz
        - LIBOFFKV_CMAKE_FLAGS=""
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
            - maven
    - os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="brew install gcc@7 && brew upgrade maven"
        - OSX_ENABLE_GCC="CC=gcc-7 && CXX=g++-7"
        - OSX_ENABLE_CLANG="CC=clang && CXX=clang++"
        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.sh"
        - SYSTEM_TRIPLET=darwin
        - PREFERED_ARCHIVE_EXTENSION=zip
        - LIBOFFKV_CMAKE_FLAGS=""
      sudo: true
    # - os: windows
    #   env:
    #     - VCPKG_TRIPLET=x64-windows
    #     - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.bat"
    #     - SYSTEM_TRIPLET=windows
    #     - PREFERED_ARCHIVE_EXTENSION=zip

before_install:
  - chmod ug+x $TRAVIS_BUILD_DIR/travis/*.sh
  - eval "${MATRIX_EVAL}"
  - eval "$OSX_ENABLE_GCC"

before_script:
  - $TRAVIS_BUILD_DIR/travis/prepare_vcpkg.sh "$HOME/vcpkg/" "${VCPKG_BOOT_EVAL}"
  - cp -r "$TRAVIS_BUILD_DIR/native/src/main/cpp/liboffkv/vcpkg/ports" "$HOME/vcpkg/"
  - cd "$HOME/vcpkg"
  - travis_wait 30 ./vcpkg upgrade --no-dry-run
  - eval "$OSX_ENABLE_CLANG"
  - travis_wait 25 ./vcpkg install gtest || $TRAVIS_BUILD_DIR/travis/export_vcpkg_logs.sh
  - travis_wait 34 ./vcpkg install ppconsul || $TRAVIS_BUILD_DIR/travis/export_vcpkg_logs.sh
  - travis_wait 25 ./vcpkg install zkpp || $TRAVIS_BUILD_DIR/travis/export_vcpkg_logs.sh
  - travis_wait 35 ./vcpkg install offscale-libetcd-cpp || $TRAVIS_BUILD_DIR/travis/export_vcpkg_logs.sh
  - rm -rf buildtrees

script:
  - cd "$TRAVIS_BUILD_DIR"
  - mvn compile -Dcmake.toolchain="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake"
  - $TRAVIS_BUILD_DIR/travis/bootstrap_etcd.sh "$SYSTEM_TRIPLET" "$PREFERED_ARCHIVE_EXTENSION"
  - $TRAVIS_BUILD_DIR/travis/bootstrap_consul.sh "$SYSTEM_TRIPLET"
  - $TRAVIS_BUILD_DIR/travis/bootstrap_zk.sh
  - mvn install -Dcmake.toolchain="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake"

after_failure:
  - $TRAVIS_BUILD_DIR/travis/send_status_message.sh
